/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2020-11-27-87ab2c4b36"
#endif /* AVUTIL_FFVERSION_H */
